package com.mightypotato.wheelie.data.local

import android.content.Context
import androidx.room.Room
import androidx.test.core.app.ApplicationProvider
import androidx.test.ext.junit.runners.AndroidJUnit4
import kotlinx.coroutines.flow.first
import kotlinx.coroutines.runBlocking
import org.junit.After
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Before
import org.junit.Test
import org.junit.runner.RunWith

/**
 * Instrumented test for [WheelDao].
 *
 * These tests run on an Android device or emulator to verify the SQL queries
 * against a real SQLite database.
 */
@RunWith(AndroidJUnit4::class)
class WheelDaoTest {

    private lateinit var database: AppDatabase
    private lateinit var wheelDao: WheelDao

    @Before
    fun createDb() {
        val context = ApplicationProvider.getApplicationContext<Context>()
        // Using an in-memory database so that the information is purged when the process is killed.
        database = Room.inMemoryDatabaseBuilder(context, AppDatabase::class.java)
            .allowMainThreadQueries()
            .build()
        wheelDao = database.wheelDao()
    }

    @After
    fun closeDb() {
        database.close()
    }

    @Test
    fun insertAndGetAllWheels() = runBlocking {
        val wheel = Wheel(name = "Test Wheel", owner = "Test Owner")
        wheelDao.insertWheel(wheel)
        val allWheels = wheelDao.getAllWheels().first()
        assertEquals(1, allWheels.size)
        assertEquals("Test Wheel", allWheels[0].name)
    }

    @Test
    fun insertDuplicateWheel_isIgnored() = runBlocking {
        val wheel1 = Wheel(name = "Unique", owner = "Owner")
        val wheel2 = Wheel(name = "Unique", owner = "Owner")
        
        wheelDao.insertWheel(wheel1)
        val result = wheelDao.insertWheel(wheel2)
        
        val allWheels = wheelDao.getAllWheels().first()
        assertEquals(1, allWheels.size)
        assertEquals(-1L, result)
    }

    @Test
    fun deleteWheel() = runBlocking {
        val wheel = Wheel(id = 1, name = "To Delete", owner = "Owner")
        wheelDao.insertWheel(wheel)
        
        // We need the ID generated by Room for deletion if not provided, 
        // but here we just delete the one we found.
        val insertedWheel = wheelDao.getAllWheels().first()[0]
        wheelDao.deleteWheel(insertedWheel)
        
        val allWheels = wheelDao.getAllWheels().first()
        assertTrue(allWheels.isEmpty())
    }

    @Test
    fun deleteWheelByName() = runBlocking {
        val wheel1 = Wheel(name = "Wheel A", owner = "Owner 1")
        val wheel2 = Wheel(name = "Wheel B", owner = "Owner 2")
        wheelDao.insertWheel(wheel1)
        wheelDao.insertWheel(wheel2)
        
        wheelDao.deleteWheelByName("Wheel A")
        
        val allWheels = wheelDao.getAllWheels().first()
        assertEquals(1, allWheels.size)
        assertEquals("Wheel B", allWheels[0].name)
    }
}
